/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.AppointmentController;
import controller.AdminController;
import controller.DoctorAppointmentController;
import DashBoard.PatientMenu;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;
import javax.swing.event.ListSelectionEvent;
import model.Appointment;
import model.Doctor;
import model.Patient;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Dao.DoctorAppointmentDao;
import java.util.Map;
import javax.swing.JOptionPane;
import model.MyAppointment;

/**
 *
 * @author adibf
 */
public class DoctorAppointmentFrame extends javax.swing.JFrame {
    Patient patient;
    ListSelectionEvent event;
    DoctorAppointmentController doctorAppointmentController;
    AppointmentController appointmentController;
    DoctorAppointmentDao docAppDao;
    List<Map<String, Object>> appointments;
    boolean checkStatus;
    
    /**
     * Creates new form DoctorAppointmentFrame
     */
    public DoctorAppointmentFrame(Patient patient) {
        initComponents();
        this.patient = patient;
        
  
        
        this.docAppDao = new DoctorAppointmentDao();
         
        DefaultTableModel tableModel = (DefaultTableModel) TableAppointment.getModel();
        this.doctorAppointmentController = new DoctorAppointmentController(this);
        
        try {
            appointments = docAppDao.getDetailedAppointments();
            loadTable(appointments);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        TextFieldSearch.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            filterTable();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filterTable();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            filterTable();
        }

        private void filterTable() {
            String searchText = TextFieldSearch.getText().toLowerCase();
            List<Map<String, Object>> filteredAppointments = appointments.stream()
                    .filter(appointment -> appointment.get("DoctorName").toString().toLowerCase().contains(searchText))
                    .collect(Collectors.toList());
            loadTable(filteredAppointments);
        }
    });
        
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAppointment = new javax.swing.JTable();
        ButtonMakeAppointment = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 165, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor Schedule");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Search Doctor");

        TableAppointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Start Session", "End Session", "Doctor's ID", "Doctor's Name", "Specialization", "Room", "Status"
            }
        ));
        jScrollPane1.setViewportView(TableAppointment);

        ButtonMakeAppointment.setText("Make an Appointment");
        ButtonMakeAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMakeAppointmentActionPerformed(evt);
            }
        });

        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextFieldSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonMakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMakeAppointment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMakeAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMakeAppointmentActionPerformed
        try {
        int selectedAppointmentIndex = TableAppointment.getSelectedRow();
        if (selectedAppointmentIndex != -1) {
            int appointmentId = (int) TableAppointment.getValueAt(selectedAppointmentIndex, 0);
            int patientId = patient.getPatientId();
            boolean checkPatient = docAppDao.notRegistered(appointmentId, patientId);
            boolean checkCap = docAppDao.isNotFull(appointmentId);
            
            if (!checkPatient) {
                JOptionPane.showMessageDialog(null, "You have registered for this appointment");
                return;
            }

            if (!checkCap) {
                JOptionPane.showMessageDialog(null, "Appointment full");
                return;
            }
            MyAppointment myAppointment = new MyAppointment(appointmentId, patientId);
            docAppDao.addMyAppointment(myAppointment);

            JOptionPane.showMessageDialog(null, "Appointment made successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please select an appointment from the appointment table");
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_ButtonMakeAppointmentActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        PatientMenu patientMenu = new PatientMenu(patient);
        patientMenu.setLocationRelativeTo(null);
        patientMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorAppointmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorAppointmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorAppointmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorAppointmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorAppointmentFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonMakeAppointment;
    private javax.swing.JTable TableAppointment;
    private javax.swing.JTextField TextFieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private int chooseAppointment(ListSelectionEvent event){
        if (!event.getValueIsAdjusting()){
            int selectedAppointment = TableAppointment.getSelectedRow();
            int selectedId;
            if (selectedAppointment != -1){
                selectedId = (int) TableAppointment.getValueAt(selectedAppointment, 0);
                return selectedId;
            }
        }
        return 0;
    }
    
    private void loadTable(List<Map<String, Object>> appointments) {
        DefaultTableModel model = (DefaultTableModel) TableAppointment.getModel();
        model.setRowCount(0);
        for (Map<String, Object> appointment : appointments) {
            String visibleStatus;
            int status = (int) appointment.get("Status");
            if (status == 0) {
                visibleStatus = "AVAILABLE";
            } else {
                visibleStatus = "FULL";
            }
            model.addRow(new Object[] {
                appointment.get("AppointmentId"),
                appointment.get("Date"),
                appointment.get("Start"),
                appointment.get("End"),
                appointment.get("DoctorId"),
                appointment.get("DoctorName"),
                appointment.get("Specialization"),
                appointment.get("Room"),
                visibleStatus
            });
        }
    } 
    
    public javax.swing.JButton getButtonMakeAppointment() {
    return ButtonMakeAppointment;
}

public void setButtonMakeAppointment(javax.swing.JButton ButtonMakeAppointment) {
    this.ButtonMakeAppointment = ButtonMakeAppointment;
}

public javax.swing.JTable getTableAppointment() {
    return TableAppointment;
}

public void setTableAppointment(javax.swing.JTable TableAppointment) {
    this.TableAppointment = TableAppointment;
}

public javax.swing.JTextField getTextFieldSearch() {
    return TextFieldSearch;
}

public void setTextFieldSearch(javax.swing.JTextField TextFieldSearch) {
    this.TextFieldSearch = TextFieldSearch;
}

public javax.swing.JLabel getJLabel1() {
    return jLabel1;
}

public void setJLabel1(javax.swing.JLabel jLabel1) {
    this.jLabel1 = jLabel1;
}

public javax.swing.JLabel getJLabel2() {
    return jLabel2;
}

public void setJLabel2(javax.swing.JLabel jLabel2) {
    this.jLabel2 = jLabel2;
}

public javax.swing.JPanel getJPanel1() {
    return jPanel1;
}

public void setJPanel1(javax.swing.JPanel jPanel1) {
    this.jPanel1 = jPanel1;
}

public javax.swing.JScrollPane getJScrollPane1() {
    return jScrollPane1;
}

public void setJScrollPane1(javax.swing.JScrollPane jScrollPane1) {
    this.jScrollPane1 = jScrollPane1;
}
}
